javac:
	#Ejecutar usando: make javac
	mkdir -p bin
	javac -d bin *.java
java:
	#Ejecutar usando: make java 1=DrawDemo
	#make java 1=DrawImageDemo
	#make java 1=PanelMgmt
	mkdir -p bin
	cd bin && java ${1}
	